### PR TITLE
Upgrade PDFBox API to v2.0.0

### PR DESCRIPTION
**Pull request by TomRoush**

### CODE REVIEW

**Comment by 4brunu** [comment]
@TomRoush thanks for you effort in creating this PR.
Can I somehow help?

**Comment by TomRoush** [comment]
@4brunu Thanks for the offer. The TestRendering test was running into OutOfMemoryExceptions on Travis CI, but I've prevented it from running in the CI process for now. The PR is merged now. I'd like to get that test working, but it's low priority and I'm not sure if that's something you would like to look into

**Comment by 4brunu** [comment]
I tried to investigate the problem but didn't came to any conclusion, sorry 😕

**Comment by 4brunu** [comment]
@TomRoush now that this PR is merged, is there any work needed to be done before releasing version 2.0, or it's just the publishing step that is missing?
Thanks 😊

**Comment by TomRoush** [comment]
It's just publishing. I should have snapshots for 2.0 out soon

**Comment by 4brunu** [comment]
Thanks 👍

**Pull request merged**
